<h1>STM Cms</h1>

<div class='homepage_block'>
	<h2>About</h2>
	<p>
	For any questions, news, bug reports and suggests<br>
	email to <a href="emailto:sgchris@gmail.com">sgchris@gmail.com</a>
	</p>
</div>



<div class='homepage_block'>
	<h2>Database</h2>
	<p>
	This very basic framework relies on MySQL database. The export file is located at the root directory<br>
	and is called <b>stm.sql.zip</b>. Create database <b>stm</b> and import the file using PhpMyAdmin (or any other MySQL client)<br>
	<br>
	If you see this page, probably you have already completed those steps.
	</p>
</div>

<div class='homepage_block'>
	<h2>Locations:</h2>
	<p>
	<b>Controllers</b> 	<br>- &lt;ROOT_DIR&gt;/application/controller/...
	<br>
	<b>Models</b> 		<br>- &lt;ROOT_DIR&gt;/application/model/...
	<br>
	<b>Views</b> 		<br>- &lt;ROOT_DIR&gt;/application/view/...
	<br>
	<b>CSS files</b> 	<br>- &lt;ROOT_DIR&gt;/Css/...
	<br>
	<b>Javascript files</b> 	<br>- &lt;ROOT_DIR&gt;/Js/...
	<br>
	<b>Images</b> 		<br>- &lt;ROOT_DIR&gt;/images/...
</div>


<div class='homepage_block'>
	<h2>Administration</h2>
	<p>
		Administration panel can be accessed via <b>.../admin/index.php</b> url path.
		The initial username and password is <b>admin/admin</b><br><br>

		The <b>left menu</b> of the admin is edited in the &lt;_HTTP_ROOT&gt;/admin/config/left_menu.php file.<br>
		(The definition is made through an array of maximum 2 levels, whereas level 1 is the main menu item
			and the 2nd level is the sub menu level (you will see it on the screen))<br><br>

		All the pages of the admin are located in &lt;ROOT_DIR&gt;/admin/pages/ directory and being accessed like:<br>
		the file:<br>
		&lt;ROOT_DIR&gt;/admin/pages/<b>books_manage.php</b><br>
		<br>
		The url:<br>
		&lt;_HTTP_ROOT&gt;/admin/<b>index.php?page=books_manage</b>

	</p>
</div>


<br><br>
<p>Full documentation will be published soon!</p>
<p>For useful online IDE, code snippets and php tutorials visit <a href="http://online-php.com" target="_blank">http://online-php.com</a><br>
<h1>Enjoy!</h1>